---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    file_cache_path: /var/chef/cache

platforms:
##
# Using a custom Vagrant box.
##
#  - name: devenv-centos-6.5
#    driver:
#      box: devenv-centos-6.5_raw
#      box_url: ../../../.boxes/devenv-centos-6.5_raw.box
#      customize:
#        memory: 2048
#        cpuexecutioncap: 50
##
# Using [OpsCode Vagrant boxes](https://github.com/opscode/bento)
##
  - name: centos-6.5
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[yum-epel]
      - recipe[chamber::prepare]
      - recipe[git]
      - recipe[java]
      - recipe[java_ext::jce]
      - recipe[chamber::default]
    attributes: {
#      java: {
#        jdk_version = '7',
#        install_flavor = 'oracle',
#        oracle: {
#          accept_oracle_download_terms: true
#        }
#      }
    }
