---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  vagrantfile_erb: .kitchen.Vagrantfile.erb
  plugins:
    cachier:
      cache:
        scope: ":box"
        auto_detect: false
        enable:
          - yum
        generic_buckets:
          - ['chef', '/var/chef/cache']
#  network:
#  - ["forwarded_port", {guest: 5601, host: 8081}]
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer
    file_cache_path: '/var/chef/cache'

platforms:
##
# Using a custom Vagrant box.
##
#  - name: devenv-centos-6.5
#    driver:
#      box: devenv-centos-6.5_raw
#      box_url: ../../../.boxes/devenv-centos-6.5_raw.box
##
# Using [OpsCode Vagrant boxes](https://github.com/opscode/bento)
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[yum-epel::default]
      - recipe[git::default]
      - recipe[chamber::default]
      - recipe[chamber::jdk]
      - recipe[chamber::maven]
      - recipe[chamber::nodejs]
      - recipe[chamber::postgresql]
      - recipe[chamber::tomcat]
      - recipe[chamber::solr]
    attributes:
    data_bags_path: "test/integration/default/data_bags"
