---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer
    file_cache_path: /var/chef/cache

platforms:
##
# Using a custom Vagrant box.
##
#  - name: devenv-centos-6.5
#    driver:
#      box: devenv-centos-6.5_raw
#      box_url: ../../../.boxes/devenv-centos-6.5_raw.box
#      customize:
#        memory: 2048
#        cpuexecutioncap: 50
##
# Using [OpsCode Vagrant boxes](https://github.com/opscode/bento)
##
  - name: centos-6.5
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[yum-epel]
      - recipe[git]
      - recipe[chamber::default]
      - recipe[chamber::jdk]
      - recipe[chamber::maven]
      - recipe[chamber::nodejs]
      - recipe[chamber::postgresql]
      - recipe[chamber::tomcat]
      - recipe[chamber::solr]
    attributes:
    data_bags_path: "test/integration/default/data_bags"
